-- =====================================================================
--  LoanPro — PostgreSQL Database Schema
-- =====================================================================
--  Target  : PostgreSQL 15+
--  Purpose : Reference DDL for the LoanPro Loan Management System.
--
--  NOTE: At runtime the application uses Hibernate with
--        `spring.jpa.hibernate.ddl-auto=update`, so these tables are
--        created automatically from the JPA entities. This file is a
--        hand-maintained mirror of that generated schema, intended for
--        documentation, manual provisioning, and review.
--
--  Money columns use NUMERIC(15,2); interest rates use NUMERIC(5,2).
--  Enum-typed columns are stored as VARCHAR (Hibernate EnumType.STRING).
-- =====================================================================

-- Run order matters because of foreign keys. Drop in reverse order for a
-- clean rebuild.
-- DROP TABLE IF EXISTS saving_goals, notifications, payments,
--     repayment_schedules, loans, documents, loan_applications,
--     loan_types, transactions, wallets, users CASCADE;

-- ---------------------------------------------------------------------
-- users — CUSTOMER and ADMIN accounts (implements Spring Security UserDetails)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password_hash     VARCHAR(255) NOT NULL,          -- BCrypt hash
    phone             VARCHAR(50),
    address           TEXT,
    nic               VARCHAR(50),
    gender            VARCHAR(20),
    marital_status    VARCHAR(20),
    city              VARCHAR(100),
    postal_code       VARCHAR(20),
    date_of_birth     DATE,
    role              VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',  -- CUSTOMER | ADMIN
    email_alerts      BOOLEAN      DEFAULT TRUE,
    sms_notifications BOOLEAN      DEFAULT FALSE,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

-- ---------------------------------------------------------------------
-- wallets — one per user, auto-created on registration
-- ---------------------------------------------------------------------
CREATE TABLE wallets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL UNIQUE REFERENCES users (id),
    wallet_id       VARCHAR(50)   NOT NULL UNIQUE,    -- e.g. WLT-2024-ADS
    balance         NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_credited  NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_debited   NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_at      TIMESTAMP
);

-- ---------------------------------------------------------------------
-- transactions — every credit/debit against a wallet
-- ---------------------------------------------------------------------
CREATE TABLE transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id   BIGINT        NOT NULL REFERENCES wallets (id),
    txn_id      VARCHAR(50)   NOT NULL UNIQUE,         -- e.g. TXN-0020
    description VARCHAR(255)  NOT NULL,
    amount      NUMERIC(15,2) NOT NULL,
    type        VARCHAR(20)   NOT NULL,                -- CREDIT | DEBIT
    category    VARCHAR(30)   NOT NULL,                -- EMI_PAYMENT | TOP_UP | TRANSFER | WITHDRAWAL | CASHBACK
    status      VARCHAR(20)   DEFAULT 'Success',
    created_at  TIMESTAMP
);
CREATE INDEX idx_transactions_wallet ON transactions (wallet_id);

-- ---------------------------------------------------------------------
-- loan_types — product catalog (seeded via data.sql)
-- ---------------------------------------------------------------------
CREATE TABLE loan_types (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(100)  NOT NULL,          -- e.g. "Personal Loan"
    code              VARCHAR(50)   NOT NULL UNIQUE,   -- e.g. "personal"
    max_limit         NUMERIC(15,2) NOT NULL,
    description       TEXT,
    min_interest_rate NUMERIC(5,2),
    max_interest_rate NUMERIC(5,2),
    active            BOOLEAN       DEFAULT TRUE
);

-- ---------------------------------------------------------------------
-- loan_applications — full 5-step application form + admin decision
-- ---------------------------------------------------------------------
CREATE TABLE loan_applications (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       VARCHAR(50)   NOT NULL UNIQUE, -- e.g. APP-0234
    user_id              BIGINT        NOT NULL REFERENCES users (id),
    loan_type_id         BIGINT        NOT NULL REFERENCES loan_types (id),

    -- Loan request
    amount_requested     NUMERIC(15,2) NOT NULL,
    purpose              VARCHAR(255),
    tenure_months        INTEGER       NOT NULL,
    status               VARCHAR(20)   NOT NULL DEFAULT 'PENDING', -- PENDING | UNDER_REVIEW | APPROVED | REJECTED

    -- Personal information (Step 2)
    full_name            VARCHAR(255)  NOT NULL,
    date_of_birth        DATE,
    address              TEXT,
    city                 VARCHAR(100),
    email                VARCHAR(255),
    nic                  VARCHAR(50),
    gender               VARCHAR(20),
    marital_status       VARCHAR(20),
    postal_code          VARCHAR(20),
    phone                VARCHAR(50),

    -- Employment information (Step 3)
    emp_status           VARCHAR(50),
    job_title            VARCHAR(100),
    work_address         TEXT,
    emp_name             VARCHAR(255),
    years_employed       INTEGER,
    work_phone           VARCHAR(50),

    -- Financial information (Step 3)
    gross_salary         NUMERIC(15,2),
    net_salary           NUMERIC(15,2),
    existing_emis        NUMERIC(15,2) DEFAULT 0,
    credit_card_payments NUMERIC(15,2) DEFAULT 0,

    -- Credit & risk
    credit_score         INTEGER,

    -- Admin decision
    approved_amount      NUMERIC(15,2),
    interest_rate        NUMERIC(5,2),
    approved_tenure      INTEGER,
    admin_remarks        TEXT,
    reviewed_by          BIGINT        REFERENCES users (id),

    submitted_at         TIMESTAMP,
    reviewed_at          TIMESTAMP,
    created_at           TIMESTAMP
);
CREATE INDEX idx_applications_user   ON loan_applications (user_id);
CREATE INDEX idx_applications_status ON loan_applications (status);

-- ---------------------------------------------------------------------
-- documents — uploaded files linked to an application (metadata only)
-- ---------------------------------------------------------------------
CREATE TABLE documents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT       NOT NULL REFERENCES loan_applications (id),
    document_type  VARCHAR(50)  NOT NULL,              -- NIC_PASSPORT | PROOF_OF_INCOME | BANK_STATEMENT | TAX_RETURN
    file_name      VARCHAR(255) NOT NULL,
    file_path      VARCHAR(500) NOT NULL,              -- relative path under uploads/
    content_type   VARCHAR(100),
    file_size      BIGINT,
    verified       BOOLEAN      DEFAULT FALSE,
    uploaded_at    TIMESTAMP
);
CREATE INDEX idx_documents_application ON documents (application_id);

-- ---------------------------------------------------------------------
-- loans — created when an application is approved (1:1 with application)
-- ---------------------------------------------------------------------
CREATE TABLE loans (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id          VARCHAR(50)   NOT NULL UNIQUE,    -- e.g. LN-84729
    user_id          BIGINT        NOT NULL REFERENCES users (id),
    application_id   BIGINT        NOT NULL UNIQUE REFERENCES loan_applications (id),
    loan_type_name   VARCHAR(100)  NOT NULL,           -- denormalized for display
    principal_amount NUMERIC(15,2) NOT NULL,
    total_payable    NUMERIC(15,2) NOT NULL,
    amount_paid      NUMERIC(15,2) NOT NULL DEFAULT 0,
    interest_rate    NUMERIC(5,2)  NOT NULL,
    tenure_months    INTEGER       NOT NULL,
    emi_amount       NUMERIC(15,2) NOT NULL,
    start_date       DATE          NOT NULL,
    end_date         DATE          NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE', -- ACTIVE | COMPLETED | DEFAULTED | CLOSED
    created_at       TIMESTAMP
);
CREATE INDEX idx_loans_user ON loans (user_id);

-- ---------------------------------------------------------------------
-- repayment_schedules — one row per installment (amortization table)
-- ---------------------------------------------------------------------
CREATE TABLE repayment_schedules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id             BIGINT        NOT NULL REFERENCES loans (id),
    installment_number  INTEGER       NOT NULL,
    due_date            DATE          NOT NULL,
    emi_amount          NUMERIC(15,2) NOT NULL,
    principal_component NUMERIC(15,2) NOT NULL,
    interest_component  NUMERIC(15,2) NOT NULL,
    remaining_balance   NUMERIC(15,2) NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'PENDING' -- PAID | NEXT_DUE | PENDING | OVERDUE | FAILED
);
CREATE INDEX idx_schedules_loan ON repayment_schedules (loan_id);

-- ---------------------------------------------------------------------
-- payments — actual EMI payments made by customers
-- ---------------------------------------------------------------------
CREATE TABLE payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_id              VARCHAR(50)   NOT NULL UNIQUE,  -- e.g. TXN-PAY-0001
    loan_id             BIGINT        NOT NULL REFERENCES loans (id),
    user_id             BIGINT        NOT NULL REFERENCES users (id),
    payment_date        DATE          NOT NULL,
    total_amount        NUMERIC(15,2) NOT NULL,
    principal_component NUMERIC(15,2) NOT NULL,
    interest_component  NUMERIC(15,2) NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'PAID', -- PAID | FAILED | REFUNDED ...
    created_at          TIMESTAMP
);
CREATE INDEX idx_payments_user ON payments (user_id);
CREATE INDEX idx_payments_loan ON payments (loan_id);

-- ---------------------------------------------------------------------
-- notifications — in-app notifications
-- ---------------------------------------------------------------------
CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    title      VARCHAR(255) NOT NULL,
    message    TEXT         NOT NULL,
    type       VARCHAR(20)  NOT NULL DEFAULT 'INFO', -- SUCCESS | WARNING | INFO | DANGER
    is_read    BOOLEAN      DEFAULT FALSE,
    created_at TIMESTAMP
);
CREATE INDEX idx_notifications_user ON notifications (user_id);

-- ---------------------------------------------------------------------
-- saving_goals — customer-created saving targets shown on the wallet page
-- ---------------------------------------------------------------------
CREATE TABLE saving_goals (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL REFERENCES users (id),
    label          VARCHAR(100)  NOT NULL,
    current_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    target_amount  NUMERIC(15,2) NOT NULL,
    color          VARCHAR(20),                        -- hex string for the progress bar
    created_at     TIMESTAMP
);
CREATE INDEX idx_saving_goals_user ON saving_goals (user_id);
